import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import FirstNav from "./_components/FirstNav/FirstNav";
import { TiShoppingCart } from "react-icons/ti";
import { Toaster } from "@/components/ui/toast"
import MyProvider from "./_components/MyProvider/MyProvider";
import Providers from "./_components/TanstackProvider/TanstackProvider";


{/* <TiShoppingCart  /> */}
const FontExo = Exo({
  variable: "--font-Exo",
  subsets: ["latin"],
  weight: ["400", "100", "700"],
});

export const metadata: Metadata = {
  title :" FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${FontExo.className}  antialiased`}
    >
      <body className="">
        <Providers>
        <MyProvider>
        
       
       <FirstNav/> 
      <Navbar/>
        
        <div className='container mx-auto px-4'>
          {children}  
          <Toaster />
        </div>
        <Footer/>
        
        </MyProvider>
        </Providers>
        </body>
    </html>
  );
}
